# classifier_runner.py
import os
import json
import logging
import asyncio
import socket
import uuid
from contextlib import asynccontextmanager
from typing import Optional, Dict, Any
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import httpx
from redis.asyncio import Redis
from redis.exceptions import ResponseError

# ----------------------------
# Logging
# ----------------------------
logging.basicConfig(level=logging.INFO, format="%(levelname)-9s %(message)s")
logger = logging.getLogger("classify")

# ----------------------------
# Env config
# ----------------------------
# AI_PROVIDER: "ollama" (default) or "openai" (LocalAI / OpenAI-compatible)
AI_PROVIDER = os.getenv("AI_PROVIDER", "ollama").strip().lower()

# Base URLs:
# - For Ollama (docker compose service name): http://ollama:11434
# - For LocalAI/OpenAI-compatible: http://localai:8080/v1  (must end with /v1)
AI_BASE_URL = os.getenv(
    "AI_BASE_URL",
    "http://ollama:11434" if AI_PROVIDER == "ollama" else "http://localai:8080/v1",
).rstrip("/")

# Default models
AI_MODEL = os.getenv(
    "AI_MODEL",
    "qwen2.5:3b-instruct" if AI_PROVIDER == "ollama" else "mistral:instruct",
)

# Optional API key for OpenAI-compatible servers (ignored by Ollama)
AI_API_KEY = os.getenv("AI_API_KEY", "").strip()

# Generation settings
AI_TEMPERATURE = float(os.getenv("AI_TEMPERATURE", "0"))
AI_NUM_CTX = int(os.getenv("AI_NUM_CTX", "4096"))
AI_TIMEOUT_SECS = float(os.getenv("AI_TIMEOUT_SECS", "120"))
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
REDIS_STREAM = os.getenv("REDIS_CLASSIFY_STREAM", "clankr:queue:classify")
REDIS_GROUP = os.getenv("REDIS_CLASSIFY_GROUP", "classifier")
REDIS_RESULT_STREAM = os.getenv("REDIS_RESULT_STREAM", "clankr:events:results")
REDIS_VISIBILITY_TIMEOUT_MS = int(os.getenv("REDIS_VISIBILITY_TIMEOUT_MS", "3600000"))

# ----------------------------
# Prompts
# ----------------------------
SYS = (
    "You are a careful content-provenance judge. "
    "Given song LYRICS, estimate if they were generated by an AI model. "
    "Return STRICT JSON only."
)

USER_TMPL = """LYRICS:
{lyrics}

Return STRICT JSON with keys:
- ai_probability: float in [0,1]
- label: one of ["AI-likely","Human","Uncertain"]
- rationale: <=2 short sentences (surface cues only)
No extra text or markdown fences — JSON only.
"""

# ----------------------------
# FastAPI app
# ----------------------------
app = FastAPI()


class LyricsInput(BaseModel):
    lyrics: str


@app.get("/health")
async def health():
    try:
        await app.state.redis.ping()
        if app.state.worker_task.done():
            raise RuntimeError("Redis worker is not running")
        return {"status": "ok", "redis": "ok"}
    except Exception as exc:
        return JSONResponse(status_code=503, content={"status": "unavailable", "error": str(exc)})


@app.get("/health/llm")
async def llm_health():
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            if AI_PROVIDER == "ollama":
                r = await client.get(f"{AI_BASE_URL}/api/tags")
                ok = r.status_code == 200
                body = r.json() if ok else {"status_code": r.status_code}
                return {"ok": ok, "provider": "ollama", "models": body}
            else:
                # OpenAI/LocalAI-compatible
                headers = _auth_header()
                r = await client.get(f"{AI_BASE_URL}/models", headers=headers)
                ok = r.status_code == 200
                body = r.json() if ok else {"status_code": r.status_code}
                return {"ok": ok, "provider": "openai", "models": body}
    except Exception as e:
        return {"ok": False, "provider": AI_PROVIDER, "error": str(e), "base_url": AI_BASE_URL}


def _auth_header() -> Dict[str, str]:
    return {"Authorization": f"Bearer {AI_API_KEY}"} if (AI_PROVIDER != "ollama" and AI_API_KEY) else {}


# ----------------------------
# LLM calls
# ----------------------------
async def _ask_llm(lyrics: str) -> Dict[str, Any]:
    """
    Ask the model to return a JSON object containing:
      { "ai_probability": float, "label": "AI-likely"|"Human"|"Uncertain", "rationale": "..."}
    """
    if not lyrics or not lyrics.strip():
        raise HTTPException(status_code=400, detail="Empty lyrics")

    sys_msg = {"role": "system", "content": SYS}
    user_msg = {"role": "user", "content": USER_TMPL.format(lyrics=lyrics)}

    if AI_PROVIDER == "ollama":
        payload = {
            "model": AI_MODEL,
            "stream": False,
            "messages": [sys_msg, user_msg],
            "options": {"temperature": AI_TEMPERATURE, "num_ctx": AI_NUM_CTX},
        }
        async with httpx.AsyncClient(timeout=AI_TIMEOUT_SECS) as client:
            res = await client.post(f"{AI_BASE_URL}/api/chat", json=payload)
            try:
                res.raise_for_status()
            except httpx.HTTPStatusError as e:
                logger.error("Ollama error: %s | body=%s", e, getattr(e.response, "text", "")[:500])
                logger.info(e)
                raise HTTPException(status_code=502, detail="Model server error (ollama)")
            j = res.json()
            content = (j.get("message") or {}).get("content", "").strip()
    # else:
    #     # OpenAI/LocalAI-compatible
    #     payload = {
    #         "model": AI_MODEL,
    #         "temperature": AI_TEMPERATURE,
    #         "response_format": {"type": "json_object"},
    #         "messages": [sys_msg, user_msg],
    #     }
    #     async with httpx.AsyncClient(timeout=AI_TIMEOUT_SECS) as client:
    #         res = await client.post(
    #             f"{AI_BASE_URL}/chat/completions",
    #             headers=_auth_header(),
    #             json=payload,
    #         )
    #         try:
    #             res.raise_for_status()
    #         except httpx.HTTPStatusError as e:
    #             logger.error("OpenAI-compatible error: %s | body=%s", e, getattr(e.response, "text", "")[:500])
    #             raise HTTPException(status_code=502, detail="Model server error (openai-compatible)")
    #         j = res.json()
    #         content = j["choices"][0]["message"]["content"].strip()

    # Parse the model JSON (with code-fence fallback)
    data = _parse_json_loose(content)

    # Sanitize fields
    p = data.get("ai_probability")
    try:
        p = float(p) if p is not None else None
    except Exception:
        p = None
    if p is not None:
        p = max(0.0, min(1.0, p))

    label = (data.get("label") or "").strip()
    return {"ai_probability": p, "label": label}


def _parse_json_loose(s: str) -> Dict[str, Any]:
    try:
        return json.loads(s)
    except Exception:
        pass
    if "```" in s:
        parts = s.split("```")
        # try the first JSON-looking chunk from the back
        for chunk in reversed(parts):
            chunk = chunk.strip()
            if chunk.startswith("{") and chunk.endswith("}"):
                try:
                    return json.loads(chunk)
                except Exception:
                    continue
    # last resort: extract a substring that looks like JSON object
    start = s.find("{")
    end = s.rfind("}")
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(s[start : end + 1])
        except Exception:
            return {}
    return {}


def _collapse_to_two_fields(judge: Dict[str, Any]) -> Dict[str, Any]:
    """
    Reduce judge output to exactly:
      { "classification": "AI"|"Human", "accuracy": float }
    """
    p = judge.get("ai_probability")
    try:
        p = float(p) if p is not None else None
    except Exception:
        p = None
    if p is not None:
        p = max(0.0, min(1.0, p))

    raw = (judge.get("label") or "").lower()
    if raw.startswith("ai"):
        classification = "AI"
    elif raw == "human":
        classification = "Human"
    else:
        # fallback by probability or default to 0.5 if missing
        if p is None:
            p = 0.5
        classification = "AI" if p > 0.5 else "Human"

    accuracy = p if classification == "AI" else (1.0 - p)
    return {"classification": classification, "accuracy": round(float(accuracy), 4)}


async def process_task(task: dict) -> dict:
    if task.get("stage") != "classify":
        raise ValueError(f"Classifier cannot process stage {task.get('stage')}")
    lyrics = task.get("lyrics")
    if not lyrics or not lyrics.strip():
        raise ValueError("Classification task is missing lyrics")

    logger.info("🟦Classifying Lyrics (%s) model=%s", AI_PROVIDER, AI_MODEL)
    judge = await _ask_llm(lyrics)
    out = _collapse_to_two_fields(judge)
    logger.info("🟦Result: %s (accuracy=%s)", out["classification"], out["accuracy"])
    return out


async def ensure_group(redis: Redis) -> None:
    try:
        await redis.xgroup_create(REDIS_STREAM, REDIS_GROUP, id="0-0", mkstream=True)
    except ResponseError as exc:
        if "BUSYGROUP" not in str(exc):
            raise


async def next_message(redis: Redis, consumer: str):
    claimed = await redis.xautoclaim(
        REDIS_STREAM,
        REDIS_GROUP,
        consumer,
        min_idle_time=REDIS_VISIBILITY_TIMEOUT_MS,
        start_id="0-0",
        count=1,
    )
    if len(claimed) > 1 and claimed[1]:
        return claimed[1][0]
    batches = await redis.xreadgroup(
        REDIS_GROUP,
        consumer,
        {REDIS_STREAM: ">"},
        count=1,
        block=5000,
    )
    return batches[0][1][0] if batches and batches[0][1] else None


async def publish_event(redis: Redis, event: dict) -> None:
    await redis.xadd(
        REDIS_RESULT_STREAM,
        {"payload": json.dumps(event, separators=(",", ":"))},
        maxlen=10000,
        approximate=True,
    )


async def worker_loop(redis: Redis, stop: asyncio.Event) -> None:
    consumer = f"classifier-{socket.gethostname()}-{uuid.uuid4().hex[:8]}"
    logger.info("Redis worker starting: %s", consumer)
    while not stop.is_set():
        message = await next_message(redis, consumer)
        if not message:
            continue
        message_id, fields = message
        task = json.loads(fields["payload"])
        base_event = {"task_id": task["task_id"], "job_id": task["job_id"], "stage": "classify"}
        try:
            await publish_event(redis, {**base_event, "event": "started"})
            result = await process_task(task)
            await publish_event(redis, {**base_event, "event": "completed", "ok": True, "result": result})
        except Exception as exc:
            logger.exception("Classifier task %s failed", task.get("task_id"))
            await publish_event(
                redis,
                {**base_event, "event": "completed", "ok": False, "error": str(exc), "result": {}},
            )
        await redis.xack(REDIS_STREAM, REDIS_GROUP, message_id)


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.redis = Redis.from_url(REDIS_URL, decode_responses=True)
    await app.state.redis.ping()
    await ensure_group(app.state.redis)
    app.state.stop_event = asyncio.Event()
    app.state.worker_task = asyncio.create_task(worker_loop(app.state.redis, app.state.stop_event))
    try:
        yield
    finally:
        app.state.stop_event.set()
        app.state.worker_task.cancel()
        await asyncio.gather(app.state.worker_task, return_exceptions=True)
        await app.state.redis.aclose()


app.router.lifespan_context = lifespan
